### ISSUE TITLE
How to "Add a text file in dicts with the same two-letters code"? I don't understand this step.

### ISSUE THREAD

**Issue by Cabbagehust2507** [Belval/TextRecognitionDataGenerator#100]
I try to add Japanese but I can't understand step "Add a text file in dicts with the same two-letters code". How can I get file txt with two-letters code?

**Comment by Belval** [comment]
So to add a new language (sorry the doc is most definitely a work in progress at this point) you want to:

1. Clone the project
2. Add a dictionary file containing Japanese words separated by newlines in `trdg/dicts/jp.txt`
```
うこん
うさぎ
うしなう
うしろがみ
うすい
うすぎ
うすぐらい
うすめる
うせつ
うちあわせ
うちがわ
うちき
うちゅう
うっかり
うつくしい
うったえる
うつる
うどん
うなぎ
うなじ
うなずく
うなる
うねる
うのう
うぶげ
うぶごえ
```
(Taken from [here](https://github.com/bitcoin/bips/blob/master/bip-0039/japanese.txt))
3. Add fonts for Japanese fonts to the font directory in `trdg/fonts/jp/`
4 Call `trdg` with `-l jp`

When installing using `pip3` the process ends up a little bit tedious, fortunately there are CLI arguments to do it manually.

`trdg -c 100 --input-file jp.txt --font your-font.ttf`

**Comment by AnakTeka** [comment]
How should I add a new font if the library was installed from pip and I want to interact through python script?

**Comment by Belval** [comment]
If you want to add a font, you'd have to add it to the relevant directory, wherever `trdg` is installed on your system.

When using the python module, you can simply give it a list of fonts to use:

```py
import os
from trdg.generators import GeneratorFromStrings

FONTS_PATH = '/your/font/path`

generator = GeneratorFromStrings(
    ['Test1', 'Test2', 'Test3'],
    fonts=[os.path.join(FONTS_PATH, font) for font in os.listdir(FONTS_PATH)]
)

for img in generator:
    # Do something with the pillow image here.
```

@AnakTeka tell me if that answers your question.

Partial reference: https://textrecognitiondatagenerator.readthedocs.io/en/latest/module.html
