### ISSUE TITLE
What do you think about creating options that control the spacing between characters?

### ISSUE THREAD

**Issue by insujung** [Belval/TextRecognitionDataGenerator#104]
In this project, it seems that there is an option for the spacing between word and word, but there is no option to control the options between letters, so do you have any idea to add this?

**Comment by Belval** [comment]
There is no such feature in TRDG at the present time, but I would be willing to accept a PR for it and/or work on it myself.

I think it could be as simple as adding a `-ls`/`--letter_spacing` parameter to the CLI and change the font rendering code to render each letter separately when `args.letter_spacing != 0` (or 1?).

What do you think?

**Comment by insujung** [comment]
Thank you for your comment.
I am thinking of giving space(" ") as much as the value of `letter_spacing` or giving space as a given width instead of space, but I think there are pros and cons of both.
I think giving space(" ") is good in that the gap changes to a constant size. when the size is converted, and the method of specifying the width is good in terms of accuracy.

**Comment by Belval** [comment]
I am working on an implementation of the feature, it will be merged tonight or tomorrow.

The `-cs` or `--character_spacing` is the argument you want. It defines the pixel count between two letters.

Here are some samples of the output, respectively 0, 5, 10 and 20.

![The quick brown fox jumps over the lazy dog_0](https://user-images.githubusercontent.com/5399488/69505810-c439f680-0ef9-11ea-9031-988ef07fd43c.jpg)
![The quick brown fox jumps over the lazy dog_5](https://user-images.githubusercontent.com/5399488/69505813-c7cd7d80-0ef9-11ea-8ac1-1a36538bf2b7.jpg)
![The quick brown fox jumps over the lazy dog_10](https://user-images.githubusercontent.com/5399488/69505814-cac86e00-0ef9-11ea-9e48-2774e19aa604.jpg)
![The quick brown fox jumps over the lazy dog_20](https://user-images.githubusercontent.com/5399488/69505819-cc923180-0ef9-11ea-9b5e-f91b9a2744ea.jpg)

Disregard the changing font.

**Comment by Belval** [comment]
Version 1.3.1 contains the changes described above. Any feedback is appreciated.

**Comment by insujung** [comment]
Thanks so much.
