### ISSUE TITLE
Does this work on Windows ?

### ISSUE THREAD

**Issue by Ownmarc** [Belval/TextRecognitionDataGenerator#109]
Does this work on Windows ? Can't see anything about it in the readme and it is not working after pip installing it.

Thanks

**Comment by Belval** [comment]
It does, but you have to download poppler separately. See the "Installation" section of the README for details.

**Comment by Ownmarc** [comment]
I already have poppler since I use it with tesseract

Its me or there is no "Installation" section in the readme ? I can't see it ahah. Went on the doc website too and didn't see anything about Windows/Poppler

**Comment by Belval** [comment]
My bad, I received this as an email and I thought it was about pdf2image, another repository.

It should absolutely work on Windows but it is not covered by tests in Travis so it is possible that the current package breaks on Windows.

I will spin up my Windows machine and try to reproduce your issue.

**Comment by Ownmarc** [comment]
Looks like it doesn't install in path. Tried it on windows 7 and windows 10

**Comment by Belval** [comment]
It does install in PATH, but it does not install an actual .exe file.

My bad, in its current form this cannot work on Windows with a simple pip install. I will attempt to fix it ASAP.

In the meantime, you can simply clone the project and call `python3 .\trdg\bin\trdg` and it will work.

You can also execute it from your script directory where pip installed it `python C:\\Python37\Scripts\trdg`.

**Comment by Belval** [comment]
Reopening as I would rather have your confirmation that it works now.

`pip3 install trdg==1.3.2` should fix the issue.

Thank you for bringing this to my attention.

**Comment by Ownmarc** [comment]
Yep, all working now, thanks
