### ISSUE TITLE
Missing modules for handwritten text generation.

### ISSUE THREAD

**Issue by zhuliqian** [Belval/TextRecognitionDataGenerator#12]
run python run.py -w 5 -f 64

**Comment by Belval** [comment]
Please copy and paste the exact stack trace you had.

**Comment by zhuliqian** [comment]
using Python3.5
only this sentence.
can generate images,but don't have label.txt

**Comment by Belval** [comment]
Generating a labels.txt file is not the default behaviour. Add `-na 2` to your command.

**Comment by zhuliqian** [comment]
thanks
