### ISSUE TITLE
How to change the color?

### ISSUE THREAD

**Issue by Lowlowlowlowlowlow** [Belval/TextRecognitionDataGenerator#121]
Hi.When I use the repo to generate seven segment dispaly number,I can only get black characters.Could anyone tell me how can I change it to red?Thank you very much.

**Comment by Belval** [comment]
This should work: `trdg -c 1 -tc '#FF0000'`

**Comment by Lowlowlowlowlowlow** [comment]
@Belval Thank you! It helps a lot.
