### ISSUE TITLE
Generate training pictures for Tibetan ocr

### ISSUE THREAD

**Issue by hsyy673150343** [Belval/TextRecognitionDataGenerator#122]
The result of generating ocr training pictures for Tibetan is as follows, with extra spaces between the text。There should be no spaces in the text of the picture！I have set --space_width=0, what is the reason for this?
![9](https://user-images.githubusercontent.com/49397302/76678893-be862f00-6616-11ea-937b-e687d85e70cc.jpg)

**Comment by Belval** [comment]
TextRecognitionDataGenerator uses Pillow to render text. Unfortunately, Pillow has very weak support for ligatures in non-western languages (Hindi and Arabic for example).

You need libraqm for it to work (as far as I know). I can write you a little guide, but I would need a font file and a small dictionary of Tibetan words.

**Comment by hsyy673150343** [comment]
> TextRecognitionDataGenerator uses Pillow to render text. Unfortunately, Pillow has very weak support for ligatures in non-western languages (Hindi and Arabic for example).
> 
> You need libraqm for it to work (as far as I know). I can write you a little guide, but I would need a font file and a small dictionary of Tibetan words.

Thank you！

**Comment by hsyy673150343** [comment]
> TextRecognitionDataGenerator uses Pillow to render text. Unfortunately, Pillow has very weak support for ligatures in non-western languages (Hindi and Arabic for example).
> 
> You need libraqm for it to work (as far as I know). I can write you a little guide, but I would need a font file and a small dictionary of Tibetan words.

Can you give me your email? I send the font file and small Tibetan text to your mailbox.

**Comment by hsyy673150343** [comment]
a font file and a small string of Tibetan words should be download in this link.[a font file and a small dictionary of Tibetan words.](url)

**Comment by hsyy673150343** [comment]
> TextRecognitionDataGenerator uses Pillow to render text. Unfortunately, Pillow has very weak support for ligatures in non-western languages (Hindi and Arabic for example).
> 
> You need libraqm for it to work (as far as I know). I can write you a little guide, but I would need a font file and a small dictionary of Tibetan words.

a font file and a small string of Tibetan words should be download in this link.[](https://github.com/hsyy673150343/FontFileAndTibetanWordFile)

**Comment by hsyy673150343** [comment]
> TextRecognitionDataGenerator uses Pillow to render text. Unfortunately, Pillow has very weak support for ligatures in non-western languages (Hindi and Arabic for example).
> 
> You need libraqm for it to work (as far as I know). I can write you a little guide, but I would need a font file and a small dictionary of Tibetan words.

https://github.com/hsyy673150343/FontFileAndTibetanWordFile

**Comment by hsyy673150343** [comment]
> TextRecognitionDataGenerator uses Pillow to render text. Unfortunately, Pillow has very weak support for ligatures in non-western languages (Hindi and Arabic for example).
> 
> You need libraqm for it to work (as far as I know). I can write you a little guide, but I would need a font file and a small dictionary of Tibetan words.
Thank you！a font file and a small string of Tibetan words should be download in this link.
https://github.com/hsyy673150343/FontFileAndTibetanWordFile

**Comment by hsyy673150343** [comment]
> TextRecognitionDataGenerator uses Pillow to render text. Unfortunately, Pillow has very weak support for ligatures in non-western languages (Hindi and Arabic for example).
> 
> You need libraqm for it to work (as far as I know). I can write you a little guide, but I would need a font file and a small dictionary of Tibetan words.

Thank you！a font file and a small string of Tibetan words should be download in this link.
https://github.com/hsyy673150343/FontFileAndTibetanWordFile

**Comment by Belval** [comment]
![out](https://user-images.githubusercontent.com/5399488/77323464-b0f23880-6ceb-11ea-84b1-98851c29b420.png)

Does this look more like the expected result? If so there is a bug in the tool and you will have to build Pillow with libraqm.

**Comment by hsyy673150343** [comment]
> ![out](https://user-images.githubusercontent.com/5399488/77323464-b0f23880-6ceb-11ea-84b1-98851c29b420.png)
> 
> Does this look more like the expected result? If so there is a bug in the tool and you will have to build Pillow with libraqm.

Yes, this is what I expected.My computer's system is ubuntu18.04, I did not find an effective way to install the libraqm package.

**Comment by Belval** [comment]
Okay so here is how you can successfully generate Tibetan OCR data.

On Ubuntu, you need to install `libraqm-dev`:

`sudo apt install libraqm-dev`

Then you will download and build Pillow from source (because the actual package will not work for reasons unknown):

```
git clone https://github.com/python-pillow/Pillow.git
cd Pillow
git checkout 7.0.x
python3 setup.py build_ext --enable-freetype install
```

Then you can generate data with:

`trdg -c 1000 -dt TibetanStrings.txt -ft Qomolangma-UchenSarchung.ttf -na 2 --word_split`

It is very important that you always include `--word_split` otherwise trdg will default to characteur-based rendering and you will lose all the ligatures.

If you are familiar with `docker` you can skip most of the above by doing:

`docker pull belval/trdg:latest`

```
docker run -v $(pwd)/fonts/:/fonts/ \
                  -v $(pwd)/dicts/:/dicts/ \
                  -v $(pwd)/out/:/app/out/ \
                  -t trdg:latest \
                  trdg -c 10 -ft /fonts/Qomolangma-UchenSarchung.ttf -dt /dicts/TibetanString.txt --word_split -na 2
```

For the above to work, you have to create two directories `fonts/` and `dicts/` in which you will put your font and dict respectively.

If you need more help I will be happy to answer more questions.

**Comment by hsyy673150343** [comment]
> trdg -c 1000 -dt TibetanStrings.txt -ft Qomolangma-UchenSarchung.ttf -na 2 --word_split
I generate data with:trdg -c 1000 -dt TibetanStrings.txt -ft Qomolangma-UchenSarchung.ttf -na 2 --word_split
But  an error occurred----trdg: error: argument -d/--distorsion: invalid int value: 't'

**Comment by hsyy673150343** [comment]
> Okay so here is how you can successfully generate Tibetan OCR data.
> 
> On Ubuntu, you need to install `libraqm-dev`:
> 
> `sudo apt install libraqm-dev`
> 
> Then you will download and build Pillow from source (because the actual package will not work for reasons unknown):
> 
> ```
> git clone https://github.com/python-pillow/Pillow.git
> cd Pillow
> git checkout 7.0.x
> python3 setup.py build_ext --enable-freetype install
> ```
> 
> Then you can generate data with:
> 
> `trdg -c 1000 -dt TibetanStrings.txt -ft Qomolangma-UchenSarchung.ttf -na 2 --word_split`
> 
> It is very important that you always include `--word_split` otherwise trdg will default to characteur-based rendering and you will lose all the ligatures.
> 
> If you are familiar with `docker` you can skip most of the above by doing:
> 
> `docker pull belval/trdg:latest`
> 
> ```
> docker run -v $(pwd)/fonts/:/fonts/ \
>                   -v $(pwd)/dicts/:/dicts/ \
>                   -v $(pwd)/out/:/app/out/ \
>                   -t trdg:latest \
>                   trdg -c 10 -ft /fonts/Qomolangma-UchenSarchung.ttf -dt /dicts/TibetanString.txt --word_split -na 2
> ```
> 
> For the above to work, you have to create two directories `fonts/` and `dicts/` in which you will put your font and dict respectively.
> 
> If you need more help I will be happy to answer more questions.

I generate data with:trdg -c 1000 -dt TibetanStrings.txt -ft Qomolangma-UchenSarchung.ttf -na 2 --word_split
But an error occurred----trdg: error: argument -d/--distorsion: invalid int value: 't'

**Comment by hsyy673150343** [comment]
> Okay so here is how you can successfully generate Tibetan OCR data.
> 
> On Ubuntu, you need to install `libraqm-dev`:
> 
> `sudo apt install libraqm-dev`
> 
> Then you will download and build Pillow from source (because the actual package will not work for reasons unknown):
> 
> ```
> git clone https://github.com/python-pillow/Pillow.git
> cd Pillow
> git checkout 7.0.x
> python3 setup.py build_ext --enable-freetype install
> ```
> 
> Then you can generate data with:
> 
> `trdg -c 1000 -dt TibetanStrings.txt -ft Qomolangma-UchenSarchung.ttf -na 2 --word_split`
> 
> It is very important that you always include `--word_split` otherwise trdg will default to characteur-based rendering and you will lose all the ligatures.
> 
> If you are familiar with `docker` you can skip most of the above by doing:
> 
> `docker pull belval/trdg:latest`
> 
> ```
> docker run -v $(pwd)/fonts/:/fonts/ \
>                   -v $(pwd)/dicts/:/dicts/ \
>                   -v $(pwd)/out/:/app/out/ \
>                   -t trdg:latest \
>                   trdg -c 10 -ft /fonts/Qomolangma-UchenSarchung.ttf -dt /dicts/TibetanString.txt --word_split -na 2
> ```
> 
> For the above to work, you have to create two directories `fonts/` and `dicts/` in which you will put your font and dict respectively.
> 
> If you need more help I will be happy to answer more questions.

I generate data with:trdg -c 1000 -dt TibetanStrings.txt -ft Qomolangma-UchenSarchung.ttf -na 2 --word_split
But an error occurred----trdg: error: argument -d/--distorsion: invalid int value: 't'

Then, I generate data with: trdg -c 1000 -i /dicts/TibetanStrings.txt -ft /fonts/Qomolangma-UchenSarchung.ttf -na 2 --word_split
Another error occurred----trdg: error: unrecognized arguments: --word_split

**Comment by Belval** [comment]
Yep that was a typo, `-i` is the right one.

**Comment by hsyy673150343** [comment]
> Yep that was a typo, `-i` is the right one.

I generate data with:trdg -c 10 -i dicts/TibetanStrings.txt -na 2  -ft fonts/latin/Qomolangma-UchenSarchung.ttf --word_split
But an error occurred----trdg: error: unrecognized arguments: --word_split

**Comment by Belval** [comment]
Make sure that you have the latest version installed. `pip3 freeze | grep trdg` should yield `trdg==1.5.0`.

**Comment by hsyy673150343** [comment]
> Make sure that you have the latest version installed. `pip3 freeze | grep trdg` should yield `trdg==1.5.0`.

Thank you very much!
