### ISSUE TITLE
Width and height of image

### ISSUE THREAD

**Issue by SiddhardhaSaran** [Belval/TextRecognitionDataGenerator#13]
Why is the new_width being calculated in this line if it's not used anywhere else? Is it supposed to be used when resizing the image?

https://github.com/Belval/TextRecognitionDataGenerator/blob/de5be6a09b4be1c9c41f622e51972b7cd712a8b9/TextRecognitionDataGenerator/data_generator.py#L77

But the variable you are using when resizing is new_text_width.
https://github.com/Belval/TextRecognitionDataGenerator/blob/de5be6a09b4be1c9c41f622e51972b7cd712a8b9/TextRecognitionDataGenerator/data_generator.py#L78

**Comment by Belval** [comment]
Nope I'm pretty sure that this is a legitimate error, I'll fix it shortly.

Thank you!
