### ISSUE TITLE
All vertical text is black

### ISSUE THREAD

**Issue by jtwsmeal** [Belval/TextRecognitionDataGenerator#132]
Hello,

Whenever I generate vertical text images the text colour is black even when I specify another colour.  For example, when I use the command `trdg -c 1 -w 5 -f 64 -tc '#FF0000' -or 1` I obtain an image with black text when the text colour is specified to be red.

After debugging for a few hours, I realized that the `ImageDraw.Draw` object used to draw on the mask image actually draws on the text image.

**Comment by Belval** [comment]
Excellent find! I'll merge it tonight.
