### ISSUE TITLE
Extending Handwriting characters

### ISSUE THREAD

**Issue by espetro** [Belval/TextRecognitionDataGenerator#135]
Hi, I would like to extend the character set for handwriting generation to include Spanish characters (á, é, ñ, ..) and special characters as well (@, $, ..). For example, take the next generated word

![spanish word](https://i.imgur.com/gXV1pcA.jpg)

In spanish it would have one *é*, thus being "suprimiéseis". How can i do it? 🤔

> NB: Kudos for such a great tool!

**Comment by Belval** [comment]
I am afraid that it would require some literature review to find a suitable dataset. You can read more on how to train the model here: https://github.com/Grzego/handwriting-generation.

**Comment by espetro** [comment]
Okay, thanks! I'll move the issue to that repo then 😄
