### ISSUE TITLE
ETA on numbers and symbols

### ISSUE THREAD

**Issue by kulkarnivishal** [Belval/TextRecognitionDataGenerator#14]
Hi, 

Great project, could you please let me know a rough time frame for a release with numbers and symbols included?

Best,
Vishal

**Comment by Belval** [comment]
The README is outdated, numbers and symbols were implemented a few months ago.

![screenshot from 2018-07-18 09-37-30](https://user-images.githubusercontent.com/5399488/42897972-bf85963e-8a8f-11e8-8cac-51311984d42e.png)

You can either use `-rs -sym -num` or use an external text file with words containing letters and symbols (`-i your_file.txt`)

It should produce stuff like this:

 
![1](https://user-images.githubusercontent.com/5399488/42898242-991d3a46-8a90-11e8-9542-8c6cb95133ed.jpg)
![2](https://user-images.githubusercontent.com/5399488/42898243-993e460a-8a90-11e8-8645-1e6800e1d9c2.jpg)
![3](https://user-images.githubusercontent.com/5399488/42898244-995a35a4-8a90-11e8-95f5-bfee8443e3bf.jpg)
![4](https://user-images.githubusercontent.com/5399488/42898246-998aba3a-8a90-11e8-8e27-46d2fef87f6f.jpg)

Hopefully it helps.

**Comment by kulkarnivishal** [comment]
Thank you so much.

**Comment by alexng88** [comment]
Hello,
  If the generated text contains "/" and if I want to save in  '{}_{}.{}'.format(text, str(index), extension)
this format, it will cause error to save in pc.  how can I solve it?

**Comment by Belval** [comment]
Use `--name_format 2` which will create a labels.txt file instead of putting the label in the name.

**Comment by alexng88** [comment]
yes I know this.
because i assume the training data should be in '{}_{}.{}'.format(text, str(index), extension) this format so I just want the filename follow the rules.  Anyway I did the training however, it cannot recognize the text.  I already open a new issue.  Hope to get your suggestion.  Thanks!

**Comment by alexng88** [comment]
https://github.com/Belval/CRNN/issues/43

the new issue is here

**Comment by Belval** [comment]
Great, I'll go over it tomorrow.
