### ISSUE TITLE
Changing filename of image

### ISSUE THREAD

**Issue by vasanththangavel** [Belval/TextRecognitionDataGenerator#145]
while trying to change the filename of images as below code, no changes happened. i want to attach the font name to image name

![Screenshot from 2020-05-04 19-18-33](https://user-images.githubusercontent.com/46041430/80972863-411fb380-8e3c-11ea-84e7-80a12e337f42.png)

**Comment by Belval** [comment]
Make sure that TRDG is not installed on your system if you are editing `data_generator.py`. It will default to the installed version and your changes will not be used.

Juste try `pip3 uninstall trdg`

**Comment by vasanththangavel** [comment]
Thanks @Belval
