### ISSUE TITLE
Running with docker gives me error 'FileNotFoundError: [Errno 2] No such file or directory: 'dicts/en.txt''

### ISSUE THREAD

**Issue by prampey** [Belval/TextRecognitionDataGenerator#146]
`sudo docker run -v /home/prudhvirampey/Documents/test:/app/out/ -t belval/trdg:latest trdg -c 20 -w 1 -f 64`
Running the above gives me error: `FileNotFoundError: [Errno 2] No such file or directory: 'dicts/en.txt'`

**Comment by Belval** [comment]
That's very strange, I'll try to reproduce the issue on my side.

**Comment by prampey** [comment]
Post this merge, I again ran:
`sudo docker pull belval/trdg:latest`
and the above command.
Same error popping up.

**Comment by Belval** [comment]
Yeah sorry I didn't have the time to fix it last night. It should be good now (at least I can't reproduce it on my side anymore).

**Comment by prampey** [comment]
Yup, it's working. Thanks!
