### ISSUE TITLE
I got this error ,can anyone help me ?

### ISSUE THREAD

**Issue by xieyufei1993** [Belval/TextRecognitionDataGenerator#15]
1 .error:
/data/20180809/TextRecognitionDataGenerator-master/TextRecognitionDataGenerator# python run.py -i "texts/subtitle.txt" -c 100 -w 5 -e png -b 3
Missing modules for handwritten text generation.
 31%|#####################################2                                                                                  | 31/100 [00:00<00:01, 68.48it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/20180809/TextRecognitionDataGenerator-master/TextRecognitionDataGenerator/data_generator.py", line 22, in generate_from_tuple
    cls.generate(*t)
  File "/data/20180809/TextRecognitionDataGenerator-master/TextRecognitionDataGenerator/data_generator.py", line 34, in generate
    image = ComputerTextGenerator.generate(text, font, text_color)
  File "/data/20180809/TextRecognitionDataGenerator-master/TextRecognitionDataGenerator/computer_text_generator.py", line 12, in generate
    image_font = ImageFont.truetype(font=font, size=32)
  File "/data/20180809/TextRecognitionDataGenerator-master/py3env/lib/python3.4/site-packages/PIL/ImageFont.py", line 261, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/data/20180809/TextRecognitionDataGenerator-master/py3env/lib/python3.4/site-packages/PIL/ImageFont.py", line 144, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
OSError: unknown file format
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 290, in <module>
    main()
  File "run.py", line 278, in main
    ), total=args.count):
  File "/data/20180809/TextRecognitionDataGenerator-master/py3env/lib/python3.4/site-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 689, in next
    raise value
OSError: unknown file format

2.when i use my own background picture,i got the blurry picture,but i want a clear one.
![image](https://user-images.githubusercontent.com/19235054/43998241-a89fc67c-9e23-11e8-9209-10cd40d3b377.png)
![image](https://user-images.githubusercontent.com/19235054/43998244-bc14fbdc-9e23-11e8-80f1-4109e0234eb2.png)
why they got different width(ps:i use my own texts)
 Looking forward to hear from you .
@Belval

**Comment by Belval** [comment]
Hi,

1. Is the font you added a .ttf file? Because the error points to an invalid font file.

2. The image is blurry because the default image height is 32 or 64. Simply add `-f 256`, where 256 could be whatever number gives a satisfactory resolution.

**Comment by xieyufei1993** [comment]
hello,i just use this script python run.py -i "texts/subtitle.txt" -c 100 -w 5 -b 3 -e png -f 256 and I just want to generate the subtitle picture such like 
![image](https://user-images.githubusercontent.com/19235054/44080496-c8f03c06-9fde-11e8-8d94-5698e9cd5e55.png)
but now my word is still blurry in the generate picture,such like 
![image](https://user-images.githubusercontent.com/19235054/44080582-0c540522-9fdf-11e8-95f0-67b35e7093e3.png)
,what can i do to deal with it .
Looking forward to hear from you .
@Belval

**Comment by Belval** [comment]
From the top of my head I don't know so it might be a bug. I will try to get a test case today.

**Comment by Belval** [comment]
When using your own texts, the file is read line-by-line, each line being converted to an image in its given form.

The width of the generated image is indeed based on the length of the generated text. 

There isn't anything for fixed width in the current version of the project. Depending on what you want that could be arranged. Do you want:

- The extra width filled with black? 
- Should the text be centered?

**Comment by xieyufei1993** [comment]
hello,I want the extra width filled with the picture,such like 
![image](https://user-images.githubusercontent.com/19235054/44185007-6b9b7b80-a144-11e8-8164-cae64d2635a1.png)
and the text be centered.
the width will be the same.
@Belval

**Comment by Belval** [comment]
See #16

If you checkout the alignement-and-width branch you should be able to do this.

Please tell me if you run into any bug.

**Comment by xieyufei1993** [comment]
can i make the word in the white color just like the subtitle?
@Belval

**Comment by xieyufei1993** [comment]
ok,thanks for your answer. Very good job!!!

**Comment by Belval** [comment]
This is now in master, reopen if you encounter any issues.
