### ISSUE TITLE
Error on RTL words like Arabics,Farsi,...

### ISSUE THREAD

**Issue by mehdi-salehi** [Belval/TextRecognitionDataGenerator#161]

**Comment by azmat21** [comment]
solved in https://github.com/Belval/TextRecognitionDataGenerator/issues/57#issuecomment-520166501

Downloading libraqm dependencies solve the issue.

sudo apt-get install -y libraqm-dev

**Comment by Belval** [comment]
Hi! I will reopen this as I just noticed that the information is not shown anywhere. My bad.

I will include a small section in the README.

**Comment by mehdi-salehi** [comment]
THANKS.
