### ISSUE TITLE
This repo support VietNamese?

### ISSUE THREAD

**Issue by ThanhNhann** [Belval/TextRecognitionDataGenerator#162]
Thanks for value repo, I have a question that whether this repo supports Vietnamese?

**Comment by Belval** [comment]
I am not familiar with Vietnamese but from looking at the Wikipedia page it should work (but does not have official support).

You can try to get a few Vietnamese fonts from google: https://fonts.google.com/?subset=vietnamese
Then get a dictionary that contains multiple Vietnamese words. I found this one: https://github.com/duyet/vietnamese-wordlist/blob/master/Viet11K.txt but there might be a better one somewhere.

With all that downloaded, `pip3 install trdg` and finally you can call `trdg -c 100 -ft Roboto-Regular.ttf -i Viet11K.txt`. To my untrained eye the result seems fine, but you tell me:

![ả giang hồ_8](https://user-images.githubusercontent.com/5399488/88741146-e0d3a180-d10c-11ea-90e5-687d93fe01f5.jpg)
![ai điếu_29](https://user-images.githubusercontent.com/5399488/88741147-e0d3a180-d10c-11ea-95c3-ebb479b61324.jpg)
![ái hữu_35](https://user-images.githubusercontent.com/5399488/88741148-e16c3800-d10c-11ea-99ed-2dd61e1d0787.jpg)
![ám muội_54](https://user-images.githubusercontent.com/5399488/88741149-e16c3800-d10c-11ea-85b9-47583ae0f0f5.jpg)
![ánh nắng_97](https://user-images.githubusercontent.com/5399488/88741150-e16c3800-d10c-11ea-89e4-a4feb356c1fb.jpg)
![ánh sáng_98](https://user-images.githubusercontent.com/5399488/88741153-e16c3800-d10c-11ea-8c3a-715786e3ace9.jpg)

**Comment by ThanhNhann** [comment]
Thanks for reply!
