### ISSUE TITLE
how to genrate in python code?(translate cli command to python code)

### ISSUE THREAD

**Issue by wolfryu** [Belval/TextRecognitionDataGenerator#165]
Thanks for the excellent job and share!!!

how to translate cli command : trdg -l ja -i /path_to_input/test2.txt -c 100 -fd /path_to_font/fonts/ -bo -k 3

into python code?

Thank you !!!

**Comment by Belval** [comment]
`trdg`is simply and executable python3 script. You can get the same result by replacing it by `python3 run.py` after cloning the repository.
