### ISSUE TITLE
Blank char in generating Arabic?

### ISSUE THREAD

**Issue by xjock** [Belval/TextRecognitionDataGenerator#166]
![ﺍﺟﺒﺎﺭﻯ ﺍﻏﺮﺍﺱ ﻟﻠﻤﻌﻠﻤﻴﻦ ﺗﺘﻨﻮﺱ ﺟﺰﺍﺯ_65](https://user-images.githubusercontent.com/3365493/91252388-1ca36a80-e790-11ea-9a4d-1e48c1e00b16.jpg)
![ﺍﺳﺘﻄﺮﺍﺩ ﺑﺮﺍﺭﻳﻚ ﺍﻻﻃﻠﻨﻄﻰ ﺍﻟﻔﻴﻠﺒﻴﻦ ﺍﺩﻋﻴﺔ_74](https://user-images.githubusercontent.com/3365493/91252389-1dd49780-e790-11ea-8977-f4fb032f7981.jpg)
![ﺍﻓﺮﺍﺯ ﺍﻟﺤﺎﺩﺓ ﻣﻄﺒﻌﻴﺔ ﻓﻠﺬ ﺗﻘﻮﻳﺮ_68](https://user-images.githubusercontent.com/3365493/91252390-1dd49780-e790-11ea-8926-66738e0014a4.jpg)
![ﺍﻗﺼﺮ ﻧﺰﺍﻩ ﻧﻴﺐ ﺑﻌﺚ ﺑﺪﻳﮭﺔ_61](https://user-images.githubusercontent.com/3365493/91252391-1f05c480-e790-11ea-86f0-f1fd9a1a9bb8.jpg)
![ﺍﻛﻠﺔ ﺍﻟﻌﺮﻭﺱ ﻓﻠﻮ ﺭﺍﻳﺔ ﻳﻤﺎﺋﻢ_94](https://user-images.githubusercontent.com/3365493/91252392-1f05c480-e790-11ea-8152-01a6b7e5fae4.jpg)
![ﺍﻟﺘﺴﻨﻴﻢ ﺻﺎﻓﺢ ﻭﺿﻌﺎﺀ ﺍﻟﻘﺴﻢ ﻣﻴﻘﺎﻥ_92](https://user-images.githubusercontent.com/3365493/91252394-1f9e5b00-e790-11ea-945a-d4ef95d06f91.jpg)
![ﺍﻟﺮﻛﺎﺏ ﻣﺮﻗﺎﺓ ﺍﻟﺼﻮﻓﻴﺔ ﺗﻄﻮﺍﻑ ﺣﺎﺿﺖ_90](https://user-images.githubusercontent.com/3365493/91252396-2036f180-e790-11ea-9b31-5a5fd1d41ed0.jpg)
![ﺍﻟﻌﻴﺶ ﻣﺠﻠﺠﻞ ﻣﻨﺎﺻﺮﺓ ﻧﮭﺰ ﺍﻟﺒﻴﻦ_81](https://user-images.githubusercontent.com/3365493/91252399-20cf8800-e790-11ea-8fa4-2d294d6b094d.jpg)
![ﺍﻟﻮﺯﺍﺭﺓ ﻛﺴﺮﻭﻧﺔ ﻟﺒﻴﺐ ﻧﺲﺀ ﻃﺎﺋﻒ_93](https://user-images.githubusercontent.com/3365493/91252400-21681e80-e790-11ea-91b4-70d52935663f.jpg)
![ﺍﻧﺼﺮﻑ ﺛﺎﻛﻠﺔ ﺭﮬﺎﻓﺔ ﻣﻠﻴﺠﺮﺍﻡ ﻣﺴﻠﻮﻝ_69](https://user-images.githubusercontent.com/3365493/91252402-2200b500-e790-11ea-9668-6fe9a8a6db4d.jpg)
![ﺍﻭﻣﻨﻴﺒﻮﺱ ﻓﺴﻄﺎﻁ ﻭﻟﻮﺩ ﺍﻟﻌﺮﻭﺓ ﺗﺒﻴﻴﻦ_58](https://user-images.githubusercontent.com/3365493/91252404-22994b80-e790-11ea-9b68-fb2a1874c4bf.jpg)
![ﺑﺎﺫﻧﺠﺎﻥ ﺍﻋﺘﺰﺍﺯ ﺍﻟﺤﻴﺾ ﺧﺮﺍﺀ ﻣﺨﺘﻨﻖ_60](https://user-images.githubusercontent.com/3365493/91252405-2331e200-e790-11ea-98c4-663f6aee1786.jpg)
![ﺑﻄﺎﺀ ﻣﺘﺠﻠﺪ ﻣﻴﻜﺎﻧﻲ ﻣﻼﻋﻴﻦ ﺳﺎﺋﺪ_91](https://user-images.githubusercontent.com/3365493/91252411-24630f00-e790-11ea-927d-6e680ee524cf.jpg)
![ﺗﺼﺎﻏﺮ ﻓﻄﺎﻳﺮﻳﺔ ﺍﻹﺻﻼﺡ ﺍﻟﺤﺮﺍﺋﻖ ﺍﺟﺎﻧﺐ_73](https://user-images.githubusercontent.com/3365493/91252412-24fba580-e790-11ea-9536-ae8de056e150.jpg)
![ﺗﻔﺎﻋﻴﻞ ﻳﻔﻠﺢ ﺣﻄﺎﺏ ﻳﺘﻄﺮﻕ ﮬﺮﺵ_72](https://user-images.githubusercontent.com/3365493/91252413-25943c00-e790-11ea-87a4-4f90150e097e.jpg)
![ﺗﻘﺎﻭﻳﻢ ﺍﺟﺮﺍﻑ ﺍﻟﺸﺮﺍﺭﺓ ﻣﺘﺎﺟﺮ ﺍﻟﺨﻢ_63](https://user-images.githubusercontent.com/3365493/91252414-262cd280-e790-11ea-89c6-8bb7f774b954.jpg)
![ﺗﻜﺮﺍﺭ ﻣﺒﻄﺎﻥ ﺧﻨﻮﺹ ﺳﻨﺘﻴﻦ ﻧﺸﻴﻂ_85](https://user-images.githubusercontent.com/3365493/91252416-26c56900-e790-11ea-96b5-d59c965467b4.jpg)
![ﺟﻠﻴﺪﻱ ﺳﺮﻱ ﺑﻄﻰﺀ ﻧﻌﻴﻖ ﺗﻜﻠﻒ_67](https://user-images.githubusercontent.com/3365493/91252417-275dff80-e790-11ea-8ad2-74c5568e38a7.jpg)
![ﺣﺎﻳﺪ ﺍﻟﺠﮭﺪ ﻭﻗﺘﻤﺎ ﺗﻤﻮﺭﺍ ﻓﻨﺎﻧﻮﻥ_76](https://user-images.githubusercontent.com/3365493/91252427-2e850d80-e790-11ea-80d9-154090f01c51.jpg)
![ﺣﺪﺍﻓﺔ ﺻﺪﺍﻕ ﺿﻮﺀ ﻭﺍﻟﺘﺴﻮﻳﻎ ﺍﮬﺘﺰﺍﺯﺓ_87](https://user-images.githubusercontent.com/3365493/91252430-2f1da400-e790-11ea-9b7d-1ccb31cc3b77.jpg)
![ﺧﺮﺧﺮ ﮬﻴﻤﺎﻥ ﺍﻟﻤﻌﻴﺸﺔ ﺗﻨﻮﻳﻦ ﻧﻘﺎﺏ_84](https://user-images.githubusercontent.com/3365493/91252431-2fb63a80-e790-11ea-82d3-950655625800.jpg)
![ﺩﺷﻴﺶ ﺍﺑﺮﺵ ﺍﺳﻠﺌﺔ ﺳﺎﻧﺢ ﻏﺮﻣﺎﺀ_86](https://user-images.githubusercontent.com/3365493/91252435-304ed100-e790-11ea-8ea3-62d5cc2e7390.jpg)
![ﺩﻳﺮﺓ ﺍﻋﻠﻦ ﺍﻟﺜﺮﻳﺎ ﮬﺎﺭﺑﺎ ﻣﺮﺍﻛﺶ_70](https://user-images.githubusercontent.com/3365493/91252436-30e76780-e790-11ea-9a19-7a155c69d1bc.jpg)
![ﺭﻋﻦ ﺍﻟﻔﺮﺍﻏﻴﺔ ﺍﻧﮭﺰﺍﻣﻲ ﻻﻓﺢ ﺍﺳﺘﻘﺒﺎﻻ_75](https://user-images.githubusercontent.com/3365493/91252439-32189480-e790-11ea-84bb-45cc6a56fb03.jpg)
![ﺳﻜﺮﺗﺎﺓ ﻛﻔﺎﻩ ﺍﻟﺪﻳﻜﻲ ﺍﻟﺨﻮﺍﺗﻢ ﻧﻔﺞ_66](https://user-images.githubusercontent.com/3365493/91252440-3349c180-e790-11ea-9cf4-bbc5e997db7f.jpg)
![ﺷﺞ ﺟﻠﻴﺪﺓ ﻋﻴﺎﺫ ﻣﻠﺰﺯ ﺟﺎﺋﻠﻮﻥ_95](https://user-images.githubusercontent.com/3365493/91252443-33e25800-e790-11ea-97eb-107a2bad9703.jpg)
![ﻋﻀﻮﺽ ﺍﻟﻤﻐﻴﺐ ﺟﺎﻟﻮﻥ ﻣﺨﺮﻓﺔ ﺗﺮﺑﺲ_64](https://user-images.githubusercontent.com/3365493/91252444-33e25800-e790-11ea-9745-784fab970df8.jpg)
![Uploading ﻓﺨﺬﻱ ﺍﺣﺪﺍﺛﻴﺎﺕ ﻗﺒﻼ ﺧﻴﺎﺽ ﺍﻧﺠﻴﺔ_79.jpg…]()

![ﻣﻠﺤﻦ ﺗﺤﺮﻳﻒ ﺑﻴﻨﮭﻤﺎ ﺟﻔﺘﻠﻚ ﺟﺬﻭﺭ_811](https://user-images.githubusercontent.com/3365493/91252129-80796380-e78f-11ea-9b59-5c89fe26e15c.jpg)
![ﺍﻟﺴﻞ ﺷﻮﺀ ﻏﻤﺎﺯﺓ ﺳﺤﻦ ﺍﻧﮭﺰﺍﻣﻲ_632](https://user-images.githubusercontent.com/3365493/91252160-92f39d00-e78f-11ea-95b7-8ca79f0468ea.jpg)
![ﺍﻭﮬﺎﻕ ﺍﻟﺒﺆﺱ ﻣﺰﻳﻒ ﻛﻤﺨﺎ ﺣﻤﻀﻴﺔ_622](https://user-images.githubusercontent.com/3365493/91252173-9dae3200-e78f-11ea-8d3b-ef35564ea460.jpg)

**Comment by Belval** [comment]
The font file is missing a character and outputs a blank rectangle when that happens. I would suggest finding another font that supports your charset and using that instead.

As an aside, did you install `libraqm-dev`and recompile Pillow with Arabic support? Because the regenerated text seems to be missing its ligatures.
