### ISSUE TITLE
Add utf-8 character

### ISSUE THREAD

**Issue by vanchung1995** [Belval/TextRecognitionDataGenerator#169]
I want to generate image from Vietnamese but it doesnot support these characters

**Comment by Belval** [comment]
Vietnamese is supported in that nothing in the codebase prevents it from working. You will have to provide your own fonts and dictionary to TRDG. Here is a sample command:

`trdg -c 1000 -i vt.txt --font_dir your_font_dir/`

**Comment by vanchung1995** [comment]
thanks, I got it
