### ISSUE TITLE
When I try to use this repo to generate japanese text imgs, it works bad. there is no letter and char in the picture.

### ISSUE THREAD

**Issue by mppsk0** [Belval/TextRecognitionDataGenerator#170]

**Comment by Belval** [comment]
What command are you using?

**Comment by mppsk0** [comment]
docker run -v /output/path/:/app/out/ -t belval/trdg:latest trug -c 10 －l ja -w 5 -f 64



---Original---

**Comment by mppsk0** [comment]
I downloaded the japanese '.otf'  file ,run the  same command can get the japanese txt image.
