### ISSUE TITLE
Get custom color font with black border

### ISSUE THREAD

**Issue by iknoorjobs** [Belval/TextRecognitionDataGenerator#171]
Hi

I am trying to get this kind of font with white solid colour and black border. 
Link: https://drive.google.com/file/d/1dwyxDBzRDmQcjU6PL8zc924l4kFDdlKB/view?usp=sharing

I tried many fonts and what I always get is
Link: https://drive.google.com/file/d/1cJXyxB7qS6bOuPpmh3A-UDMShBLLQIG6/view?usp=sharing

Please tell how can I do this?

Thanks

**Comment by Belval** [comment]
As far as I know this is a shadow and not related to the font. If you are willing to work on it I would love a PR for that feature. Basically you would have to edit the `computer_text_generator.py` file to add a "shadow" behind the rendered text. It's doable using only Pillow.

See: https://stackoverflow.com/questions/18974194/text-shadow-with-python

Unfortunately I don't really have the time to implement it myself but it should be pretty straight-forward:

1. Get a mask of the rendered text
2. Make those pixels grey-ish
3. Resize or more the image by (x, y)
4. Paste the text on top of it.
5. Return the resulting image.

**Comment by iknoorjobs** [comment]
Hi @Belval 

I just solved this using the stroke_width and stroke_fill ([https://stackoverflow.com/questions/62737084/outline-text-on-image-in-python](url)

But now for some images, the font is truncated from bottom. Example image:
![7](https://user-images.githubusercontent.com/22852967/93845877-04a40580-fcc0-11ea-9163-a3e4007201ec.jpg)

Any idea, how to solve this?

Many thanks
Iknoor

**Comment by Belval** [comment]
Of the result is convincing enough for you that's great!

As for the weird crop, did it do that before your changes? Say you take a clean version of the repo using the same font and background?

**Comment by iknoorjobs** [comment]
Hi @Belval 

No, it was working perfectly before using these 2 parameters (stroke_width and stroke_fill). 
I was wondering if there's a margin issue messing up with these 2 parameter?

Thanks

**Comment by iknoorjobs** [comment]
Hi @Belval

I solved it by slightly increasing the text_width and text_height. 
Will soon create a PR.

Thanks

**Comment by iknoorjobs** [comment]
Hi @kimlia545 

1) Please refer to this

> Hi @Belval
> 
> I just solved this using the stroke_width and stroke_fill ([link](https://stackoverflow.com/questions/62737084/outline-text-on-image-in-python))
> 
> But now for some images, the font is truncated from bottom. Example image:
> ![7](https://user-images.githubusercontent.com/22852967/93845877-04a40580-fcc0-11ea-9163-a3e4007201ec.jpg)
> 
> Any idea, how to solve this?
> 
> Many thanks
> Iknoor


2) You can try changing line 67-68 for horizontal text in computer_text_generator.py

```
    if border:
        txt_img = Image.new("RGBA", (text_width+5, text_height+7), (0, 0, 0, 0))
        txt_mask = Image.new("RGB", (text_width+5, text_height+7), (0, 0, 0))  
```

Regards,
Iknoor

**Comment by kimlia545** [comment]
@iknoorjobs
Thank you for your answer
I found an easier way just put a font of this design
![ttf](https://user-images.githubusercontent.com/72369991/104670929-1ce0da00-5720-11eb-8769-b74e5b96e52a.png)
It work well
![0007_127982](https://user-images.githubusercontent.com/72369991/104671133-8c56c980-5720-11eb-92de-2e890b78eada.jpg)
