### ISSUE TITLE
German dictionary does not contain words with "Umlaute" (eg  ä, ö and ü)

### ISSUE THREAD

**Issue by iknoorjobs** [Belval/TextRecognitionDataGenerator#173]
Hi
Should I replace de.txt and create a PR for this?

Regards,
Iknoor

**Comment by iknoorjobs** [comment]
Sorry duplicate issue
Duplicate of #172

**Comment by Belval** [comment]
If you have a German directory on hand I would happily merge a PR!

**Comment by Belval** [comment]
Fixed by #174
