### ISSUE TITLE
when I process chinese text, and set space width equal zero, the generated img and label is not the same

### ISSUE THREAD

**Issue by UncleLLD** [Belval/TextRecognitionDataGenerator#177]
when I process chinese text, and set space width equal zero, the generated image content and image name label is not the same

code:
```shell
python run.py -c 3  -l cn -w 3 -sw 0.0
```
the output result image name label:
![image](https://user-images.githubusercontent.com/16642335/98642061-bb8b3c00-2367-11eb-8842-66a9a657d3a2.png)

but the generated image is:
![image](https://user-images.githubusercontent.com/16642335/98642083-c9d95800-2367-11eb-89ee-ac1c93c9e7ab.png)

the name of  file should not include spaces, how I solve this problem? 
and I know there should have a space in english, but there could not have a space in chinese.

Thank you!

**Comment by Belval** [comment]
That's a bug, I'll fix it by the end of the day.

Thank you!

**Comment by hiendoan95** [comment]
@Belval I'm facing the same problem when generating Japanese text. Did you fix it?

**Comment by Belval** [comment]
When running master do you still experience this issue?
