### ISSUE TITLE
hello,how can i generate vertical text like chinese characters arranged vertically?it seems -d and -do settings do not work

### ISSUE THREAD

**Issue by Redaimao** [Belval/TextRecognitionDataGenerator#18]

**Comment by Belval** [comment]
There is no such thing implemented currently, if more people wish to use this feature, please let me know.

This is rather complex as Pillow does not render line feed in its input. You'd have to create X text images and stack them.

**Comment by Belval** [comment]
See https://github.com/Belval/TextRecognitionDataGenerator/pull/29

**Comment by Belval** [comment]
Since the feature was added to the master branch 4 days ago, I will be closing this. Feel free to reopen if you need help with anything.
