### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by caoyangcr7** [Belval/TextRecognitionDataGenerator#19]
hello,thanks firstly, is there a labels.txt in the code for the generated images?

**Comment by Belval** [comment]
Using the `-na` argument: 

- 0: [TEXT]_[ID].[EXT], **NO** labels.txt, only in the filename
- 1: [ID]_[TEXT].[EXT], **NO** labels.txt only in the filename
- 2: [ID].[EXT] + one file labels.txt containing id-to-label mappings

So if you want a labels.txt simply add `-na 2` to your command.

**Comment by caoyangcr7** [comment]
Thanks very much.
