### ISSUE TITLE
Hindi Text Generation

### ISSUE THREAD

**Issue by arshv27** [Belval/TextRecognitionDataGenerator#191]
I'm trying to generate hindi text using this code. I am able to generate very few images correctly. However, most of the words  come out as just boxes. Has anyone faced this issue? If yes, how did you solve it? I'm attaching a couple of images for reference.
![B](https://user-images.githubusercontent.com/33731612/107880203-57968780-6f03-11eb-8040-e47fba468c46.jpg)
![A](https://user-images.githubusercontent.com/33731612/107880206-5bc2a500-6f03-11eb-9220-d4f51da215b5.jpg)

**Comment by Belval** [comment]
There is a probably a font that does not support the full devanagari set and this is causing issue when you generate images. What fonts are you using?

**Comment by arshv27** [comment]
@Belval Thanks for your quick response. This seems to be the issue. I had added some ttf format fonts myself (in addition to the font provided in this repo). Those were causing the issue.

1. Are you aware of other fonts that may work for the Hindi words, or how such fonts can be identified? 
2. A slightly unrelated query. I expected a labels.txt file to be created in my output directory for the label mapping. However, I don't see it after the execution of the code. Am I missing something?

**Comment by Belval** [comment]
1. Google Fonts is a wonderful resource to find fonts that support a specific language: https://fonts.google.com/?subset=devanagari
2. `labels.txt` is created only if you pick the right name format (yes the argument is poorly named). Add `--name_format 2` to your `trdg` invocation and you will get a label file.
