### ISSUE TITLE
Some Chinese characters can't be made, it shows a square,just like 口口口口口

### ISSUE THREAD

**Issue by jackie930** [Belval/TextRecognitionDataGenerator#197]
hi,

I saw this similar issue posted before and identified this was caused by fonts not support all the characters'. however, I have two follow-up questions on this:

* how do I know whether the fonts support a character or not? is there a programming way to do this?
* where did you specify the squares in the source code? I tried to locate but failed.

thanks!

**Comment by Belval** [comment]
Hi, this might help: https://stackoverflow.com/questions/47948821/python-imagefont-and-imagedraw-check-font-for-character-support at some point it should probably be implemented directly in the project.

As for the squares, it's a Pillow default and is not unique to trdg.

**Comment by jackie930** [comment]
> Hi, this might help: https://stackoverflow.com/questions/47948821/python-imagefont-and-imagedraw-check-font-for-character-support at some point it should probably be implemented directly in the project.
> 
> As for the squares, it's a Pillow default and is not unique to trdg.

super helpful! thanks!

**Comment by leduy-it** [comment]
@Belval , would it be possible to introduce a strict mode for this case? Also, may I submit a PR for this repository if that's acceptable?"
