### ISSUE TITLE
Possible to change output image to have entire background instead of cropping ?

### ISSUE THREAD

**Issue by mohammedayub44** [Belval/TextRecognitionDataGenerator#206]
Hi There,
Thanks for your great work on this repo. It has been helpful.
I'm trying to overlay random text on top of entire background images (or images) , 
Currently it looks like the output images are cropped with the generated text images width and height. Is there a way to avoid this and just overlay it on top of entire background ?

If not possible, link to other projects you know can also be helpful. 

Thanks !

**Comment by Belval** [comment]
The project is really more about generating data to train recognition models (word crops). What you are describing sounds more like this project: https://github.com/ankush-me/SynthText.

**Comment by mohammedayub44** [comment]
Thanks. It looks like what I wanted.
