### ISSUE TITLE
How can I customize the output string?

### ISSUE THREAD

**Issue by computer-rookie-master** [Belval/TextRecognitionDataGenerator#221]
If I want to customize the output string like the first word is a specific word, what should I do, need help!

**Comment by computer-rookie-master** [comment]
like license plate

**Comment by computer-rookie-master** [comment]
solved
Thanks！

**Comment by bit-scientist** [comment]
hi, @computer-rookie-master, could you explain what you did so that others can also take advantage of your contribution. Thank you.

**Comment by h-yy-bag** [comment]
> solved Thanks！

hello could u please share how to solve this problem , i'll appreciate it a lot
