### ISSUE TITLE
Generated arabic is garbage

### ISSUE THREAD

**Issue by schissmantics** [Belval/TextRecognitionDataGenerator#229]
Here's an example by running:

    trdg -c 1000 -w 5 -f 64 -l ar

Actual: ﺍﺩﺭﺍﻙ ﻋﻠﻴﻞ ﻧﺴﺎﻧﺲ ﺩﻧﺎﻭﺓ ﺍﻧﺰﺍﺡ_5

image: 

![ﺍﺩﺭﺍﻙ ﻋﻠﻴﻞ ﻧﺴﺎﻧﺲ ﺩﻧﺎﻭﺓ ﺍﻧﺰﺍﺡ_5](https://user-images.githubusercontent.com/58062537/136394270-27976631-b350-408e-90f3-fe04bc7e4f3e.jpg)

Actual: ﺍﻏﻴﺎﻥ ﻣﺨﺎﺭﺯ ﺍﻟﺸﺮﺍﺭﺓ ﻣﻨﻔﺮﺝ ﻣﺘﺠﺎﻭﺏ_3

image:

![ﺍﻏﻴﺎﻥ ﻣﺨﺎﺭﺯ ﺍﻟﺸﺮﺍﺭﺓ ﻣﻨﻔﺮﺝ ﻣﺘﺠﺎﻭﺏ_3](https://user-images.githubusercontent.com/58062537/136394448-53cd4ec2-f0b1-49bd-a7c9-6c8e661b1793.jpg)

Actual: ﺍﻟﺒﺎﻝ ﺍﺳﺘﻄﻴﺮ ﺍﻋﺪ ﻟﻴﻜﺘﺐ ﺳﻌﺪﺍﺀ_1

image: 

![ﺍﻟﺒﺎﻝ ﺍﺳﺘﻄﻴﺮ ﺍﻋﺪ ﻟﻴﻜﺘﺐ ﺳﻌﺪﺍﺀ_1](https://user-images.githubusercontent.com/58062537/136394556-74ba9053-de1a-4061-b755-b320a28c53fd.jpg)

And so on ... you get the idea

**Comment by schissmantics** [comment]
No, I didn't install them beforehand. I just tried to and for some reason, [libraqm](https://github.com/HOST-Oman/libraqm) build fails. I'm closing this issue, I'll figure out a way to install it and if the problem persists, I'll reopen it.

    The Meson build system
    Version: 0.45.1
    Source dir: /content/libraqm
    Build dir: /content/libraqm/build
    Build type: native build
    Project name: raqm
    Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
    Build machine cpu family: x86_64
    Build machine cpu: x86_64
    
    meson.build:20:6: ERROR: Unknown method "get_argument_syntax" in object.
    
    A full log can be found at /content/libraqm/build/meson-logs/meson-log.txt

**Comment by AhmadHakami** [comment]
any updates?
