### ISSUE TITLE
Alpha level/transparency for text?

### ISSUE THREAD

**Issue by ckcollab** [Belval/TextRecognitionDataGenerator#232]
Thanks so much for this project! Has helped in training my net for EasyOCR quite a bit, much appreciated!

I was wondering if there was an easy place/way to insert transparency, or a range of transparency, into the mix? I can make a very light gray font on gray background (via `background_type=2`), but I'm hoping for some of the background to come through and train my net against that..

**Comment by Belval** [comment]
With the latest version you should be able to do `trdg -c 100 -tc '#FF000000,#FF0000FF'` where the last value is transparency.
