### ISSUE TITLE
How do I add fonts in the trdg argument?

### ISSUE THREAD

**Issue by adarshsin007** [Belval/TextRecognitionDataGenerator#238]
I need to generate 1000 images per fonts, but I do not understand what should be the actual argument for loading the fonts folder.
What should I include in this line trdg -c 1000 -w 5 -f 64 for generating images If I want the images to be in Lato Font? Help Please.

**Comment by sarah-nizam** [comment]
did you figure this out?
if yes can you help me out?
I am having the same issue.

**Comment by adarshsin007** [comment]
Yes, I did.
To load the font directory folder, all we need is to use -fd font_folder (e.g. -fd fonts/en)
for example: trdg -c 10 -fd fonts/en -rs -let -num -r -sym
