### ISSUE TITLE
New Line

### ISSUE THREAD

**Issue by DoveCrying** [Belval/TextRecognitionDataGenerator#274]
Hi, is there support for new lines ("\n") while using the Handwriting generation?

**Comment by Belval** [comment]
Unfortunately no, I'd be willing to merge a PR for it, but I have very limited bandwidth to work on it myself. This is also somewhat orthogonal to how word/line recognizers are trained in the wild, where a detection model will localize the words and a recognizer model will transcribe it. Multi-line generation does not make as much sense considering the state of the art.

I don't mind merging this as a feature.

**Comment by DoveCrying** [comment]
Hi, using a workaround I've been able to make it work for my needs. Thank you.
