### ISSUE TITLE
ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by javohirss** [Belval/TextRecognitionDataGenerator#277]
```python
--> 130             )
    131             resized_img = distorted_img.resize(
--> 132                 (new_width, size - vertical_margin), Image.ANTIALIAS
    133             )
    134             resized_mask = distorted_mask.resize((new_width, size - vertical_margin), Image.NEAREST)

[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in resize(self, size, resample, box, reducing_gap)
   1881         if self.mode in ["LA", "RGBA"]:
   1882             im = self.convert(self.mode[:-1] + "a")
-> 1883             im = im.resize(size, resample, box)
   1884             return im.convert(self.mode)
   1885 

[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in resize(self, size, resample, box, reducing_gap)
   1903                 )
   1904 
-> 1905         return self._new(self.im.resize(size, resample, box))
   1906 
   1907     def reduce(self, factor, box=None):
ValueError: height and width must be > 0

```

**Comment by SilvaQ** [comment]
I also encountered this problem, the problem disappeared after setting the font, you can specify fonts dir to try

**Comment by javohirss** [comment]
Oh thx, now it works

**Comment by worldofzeroandone** [comment]
@SilvaQ @javohirss 
> I also encountered this problem, the problem disappeared after setting the font, you can specify fonts dir to try

I specify a fonts dir but still has the problem,I want to generate 450000 images,is it because of the size of generate images?expect for you reply

**Comment by worldofzeroandone** [comment]
> @SilvaQ @javohirss
> 
> > I also encountered this problem, the problem disappeared after setting the font, you can specify fonts dir to try
> 
> I specify a fonts dir but still has the problem,I want to generate 450000 images,is it because of the size of generate images?expect for you reply

this is my error:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/gxu4090x2/桌面/chengang/TRDG/trdg/data_generator.py", line 22, in generate_from_tuple
    cls.generate(*t)
  File "/home/gxu4090x2/桌面/chengang/TRDG/trdg/data_generator.py", line 133, in generate
    resized_img = distorted_img.resize(
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/site-packages/PIL/Image.py", line 2305, in resize
    im = im.resize(size, resample, box)
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/site-packages/PIL/Image.py", line 2328, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 493, in <module>
    main()
  File "run.py", line 438, in main
    for _ in tqdm(
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/gxu4090x2/.conda/envs/mm/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: height and width must be > 0
