### ISSUE TITLE
How to generate vertical images

### ISSUE THREAD

**Issue by savort** [Belval/TextRecognitionDataGenerator#28]
for example we often read words and characters from left to right.
but in Chinese, we sometimes arrange characters from top to bottom.
So I just wonder can this code generate top to bottom configuration of Chinese sentences?

**Comment by Belval** [comment]
Hi!

There is no such feature at the moment, but you are the second person to ask for it so I understand that there is a need for vertical text.

I currently have to study for my finals, but I'll add it in the next 2 weeks.

Is that good with you?

**Comment by savort** [comment]
Excellent！I'm looking forward to it!
Wish you get good grades！thx

**Comment by savort** [comment]
And can you add a parameter to define the distance between characters?

**Comment by Belval** [comment]
Please open another issue for this request.

Thank you

**Comment by Belval** [comment]
I made the following sample using the code in banch "text-orientation-and-variable-spacing". Is it the expect result?

Command for reference: `python run.py -w 10 -sw 0.5 -c 1 -or 1 -f 600 -l cn`.

I'm thinking of changing the `-f` parameters so it becomes the width in this case, does that make sense for your usecase?

![_0](https://user-images.githubusercontent.com/5399488/50194047-2a3ff600-0307-11e9-9efc-9a6ca2e917b6.jpg)

**Comment by Belval** [comment]
You need to checkout the text-orientation-and-variable-spacing branch. I cannot merge anything yet as I need to add tests as soon as I have your ok regarding this.

**Comment by savort** [comment]
Regarding the pictures you provided above, that's exactly what I want. But the -sw -or option has not been added to the code so I cannot generate the vertical pictures myself. 
I addition, I think its better for me that the distance between words be defined by a parameter.

**Comment by Belval** [comment]
I think you do not understand.

The modifications are **not** in master. They are available in the **text-orientation-and-variable-spacing** branch.

You can see those changes if you do `git checkout text-orientation-and-variable-spacing` in the cloned repository on your disk OR here on github: https://github.com/Belval/TextRecognitionDataGenerator/tree/text-orientation-and-variable-spacing

**Comment by Belval** [comment]
See https://github.com/Belval/TextRecognitionDataGenerator/pull/29

**Comment by savort** [comment]
Oh, I got it. It seems the modifications have been merged into master now. Thx

**Comment by Belval** [comment]
Closing as I assume the new feature resolves the above-mentioned issue.

Feel free to reopen if something isn't right.
