### ISSUE TITLE
how to create image with comma?

### ISSUE THREAD

**Issue by MJ2468** [Belval/TextRecognitionDataGenerator#290]
Hello! 
it is useful to create images.
However, I just figured it out that some letters are missing such as , . ! @ # $ in the image file name.
I wonder how to create file name with that letter.
Thanks for helping
 +)my language is korean

It is what happen to me.
![image](https://user-images.githubusercontent.com/97005604/190528365-00437955-6ade-4026-bad2-3e7436a6e381.png)

my purpose is to match some special characters and images.

**Comment by MohieEldinMuhammad** [comment]
@MJ2468 can you please tell me how you solved this problem ?

**Comment by MJ2468** [comment]
I used an argument 'name format'.
It happened because we cannot use special characters for make a file name.
Thus, I solved it to use the argument -na 2 and the file formet is '1.png'. You can find more detail of it through line 186 in run.py.

**Comment by MohieEldinMuhammad** [comment]
thanks a lot for your help
