### ISSUE TITLE
Generating Images similar to Oxford Synthetic Word Dataset

### ISSUE THREAD

**Issue by kevgeo** [Belval/TextRecognitionDataGenerator#30]
Hi,
I am trying to generate images containing single words similar to that in the [Oxford Synthetic Word Dataset](http://www.robots.ox.ac.uk/~vgg/data/text/). The words will also contain symbols such as colon, percentage etc. 
The process to create the Oxford dataset is described in the below image.
<img width="552" alt="process" src="https://user-images.githubusercontent.com/8247966/50471582-5d574900-09db-11e9-8c8f-2f53f076f6a6.PNG">

I am unsure how to generate such words along with symbols as I get such images below which are very much different from the ones in the Oxford dataset.
![newsynth1](https://user-images.githubusercontent.com/8247966/50478062-41f93780-09f5-11e9-81db-cde925dd75cf.jpg)
![newsynth4](https://user-images.githubusercontent.com/8247966/50478063-4291ce00-09f5-11e9-9698-8f09a604c083.jpg)

Images from Oxford dataset are given below,
![synth1](https://user-images.githubusercontent.com/8247966/50478075-4faebd00-09f5-11e9-9d88-669688c34795.jpg)
![synth2](https://user-images.githubusercontent.com/8247966/50478076-4faebd00-09f5-11e9-9be0-87b0840d1a95.jpg)

**Comment by Belval** [comment]
Hi!

First, you need to identify the type of transformation applied in the Oxford Synthetic Word Dataset.

From your example, I'd say it's mostly various fonts with an angle added to them. This should be easy enough to do.

My first bet would be to do: `python3 run.py -w 1 -c 1000 -k 20 -rk`

`-w 1` means "1 word per image"
`-c 1000` means "1000 images"
`-k 20` means "skewed 20 degrees"
`-rk` means "random skew"

You can add `-t X` where `X` is the number of thread in your CPU. This is useful to speedup the process.

But then this will generate images with always the same font color, which is not what the Oxford dataset is about!

You can add `-tc #282828,#444444` which means "A font color between #282828 (gray) and #444444 (lighter gray)"

Putting everything together you get `python3 run.py -w 1 -c 1000 -k 20 -rk -tc #282828,#444444`

For more options you can simply look at `python3 run.py -h` for a short-yet-thoughtful description of the parameter.

I will try it on my own computer a bit latter and post examples of the result.

**Comment by Belval** [comment]
Here's 8 samples I generated with the above command:

![festal_938](https://user-images.githubusercontent.com/5399488/50493141-939bc500-09e9-11e9-9de0-ae3bfb2ee0cc.jpg)
![habilimented_400](https://user-images.githubusercontent.com/5399488/50493145-972f4c00-09e9-11e9-84cb-3268da5d0c10.jpg)
![horsegate_591](https://user-images.githubusercontent.com/5399488/50493147-9bf40000-09e9-11e9-947c-159c706361c0.jpg)
![munchausenism_168](https://user-images.githubusercontent.com/5399488/50493150-a0b8b400-09e9-11e9-93ec-b1f3f4cb3af4.jpg)
![parsonages_176](https://user-images.githubusercontent.com/5399488/50493151-a8785880-09e9-11e9-8402-575256a4c392.jpg)
![phlebotomise_767](https://user-images.githubusercontent.com/5399488/50493153-af06d000-09e9-11e9-9e03-2f0fb42df88c.jpg)
![recategorize_194](https://user-images.githubusercontent.com/5399488/50493157-b62dde00-09e9-11e9-9556-d2ccac836578.jpg)
![raticides_662](https://user-images.githubusercontent.com/5399488/50493161-bb8b2880-09e9-11e9-9d91-a13b5380c1a5.jpg)

If you want to remove the gaussian noise behind the words, you can add `-b 1` for now it is only white, with more options planned.

**Comment by kevgeo** [comment]
@Belval  Thanks for the swift response :).  The images you have generated are fine but the problem arises when I want to include numbers and punctuations. I am trying to generate images similar to the ones below,
![oxford1](https://user-images.githubusercontent.com/8247966/50504151-a36ee400-0a91-11e9-88b7-b891b0c2dff1.jpg)
![oxford2](https://user-images.githubusercontent.com/8247966/50504152-a36ee400-0a91-11e9-8a48-b7eb63a02f37.jpg)

But my generated images are like below where the font of the words does not look similar to those in the dataset or to your generated images .
![newsynth4](https://user-images.githubusercontent.com/8247966/50504344-0614af80-0a93-11e9-8e0c-1d6ac449df3f.jpg)
![newsynth6](https://user-images.githubusercontent.com/8247966/50504345-06ad4600-0a93-11e9-8e05-e89c673785b7.jpg)

**Comment by Belval** [comment]
What exact command are you using?

**Comment by kevgeo** [comment]
@Belval Sorry for the late reply. I have edited the arguments in run.py . Here are the list of arguments with values for clarity.
`   

    def parse_arguments():
    #Parse the command line arguments of the program.

    parser = argparse.ArgumentParser(description='Generate synthetic text data for text recognition.')
    parser.add_argument(
        "--output_dir",
        type=str,
        nargs="?",
        help="The output directory",
        default="out/",
    )
    parser.add_argument(
        "-i",
        "--input_file",
        type=str,
        nargs="?",
        help="When set, this argument uses a specified text file as source for the text",
        default=""
    )
    parser.add_argument(
        "-l",
        "--language",
        type=str,
        nargs="?",
        help="The language to use, should be fr (French), en (English), es (Spanish), de (German), or cn (Chinese).",
        default="en"
    )
    parser.add_argument(
        "-c",
        "--count",
        type=int,
        nargs="?",
        help="The number of images to be created.",
        default=1000
    )
    parser.add_argument(
        "-rs",
        "--random_sequences",
        action="store_true",
        help="Use random sequences as the source text for the generation. Set '-let','-num','-sym' to use letters/numbers/symbols. If none specified, using all three.",
        default=True
    )
    parser.add_argument(
        "-let",
        "--include_letters",
        action="store_true",
        help="Define if random sequences should contain letters. Only works with -rs",
        default=True
    )
    parser.add_argument(
        "-num",
        "--include_numbers",
        action="store_true",
        help="Define if random sequences should contain numbers. Only works with -rs",
        default=True
    )
    parser.add_argument(
        "-sym",
        "--include_symbols",
        action="store_true",
        help="Define if random sequences should contain symbols. Only works with -rs",
        default=True
    )
    parser.add_argument(
        "-w",
        "--length",
        type=int,
        nargs="?",
        help="Define how many words should be included in each generated sample. If the text source is Wikipedia, this is the MINIMUM length",
        default=1
    )
    parser.add_argument(
        "-r",
        "--random",
        action="store_true",
        help="Define if the produced string will have variable word count (with --length being the maximum)",
        default=False
    )
    parser.add_argument(
        "-f",
        "--format",
        type=int,
        nargs="?",
        help="Define the height of the produced images",
        default=32,
    )
    parser.add_argument(
        "-t",
        "--thread_count",
        type=int,
        nargs="?",
        help="Define the number of thread to use for image generation",
        default=3,
    )
    parser.add_argument(
        "-e",
        "--extension",
        type=str,
        nargs="?",
        help="Define the extension to save the image with",
        default="jpg",
    )
    parser.add_argument(
        "-k",
        "--skew_angle",
        type=int,
        nargs="?",
        help="Define skewing angle of the generated text. In positive degrees",
        default=10,
    )
    parser.add_argument(
        "-rk",
        "--random_skew",
        action="store_true",
        help="When set, the skew angle will be randomized between the value set with -k and it's opposite",
        default=True,
    )
    parser.add_argument(
        "-wk",
        "--use_wikipedia",
        action="store_true",
        help="Use Wikipedia as the source text for the generation, using this paremeter ignores -r, -n, -s",
        default=False,
    )
    parser.add_argument(
        "-bl",
        "--blur",
        type=int,
        nargs="?",
        help="Apply gaussian blur to the resulting sample. Should be an integer defining the blur radius",
        #default = 0.7,
        default=0,
    )
    parser.add_argument(
        "-rbl",
        "--random_blur",
        action="store_true",
        help="When set, the blur radius will be randomized between 0 and -bl.",
        default = 0.5,
        #default=False,
    )
    parser.add_argument(
        "-b",
        "--background",
        type=int,
        nargs="?",
        help="Define what kind of background to use. 0: Gaussian Noise, 1: Plain white, 2: Quasicrystal, 3: Pictures",
        default=0,
    )
    parser.add_argument(
        "-hw",
        "--handwritten",
        action="store_true",
        help="Define if the data will be \"handwritten\" by an RNN",
    )
    parser.add_argument(
        "-na",
        "--name_format",
        type=int,
        help="Define how the produced files will be named. 0: [TEXT]_[ID].[EXT], 1: [ID]_[TEXT].[EXT] 2: [ID].[EXT] + one file labels.txt containing id-to-label mappings",
        default=0,
    )
    parser.add_argument(
        "-d",
        "--distorsion",
        type=int,
        nargs="?",
        help="Define a distorsion applied to the resulting image. 0: None (Default), 1: Sine wave, 2: Cosine wave, 3: Random",
        default=0
    )
    parser.add_argument(
        "-do",
        "--distorsion_orientation",
        type=int,
        nargs="?",
        help="Define the distorsion's orientation. Only used if -d is specified. 0: Vertical (Up and down), 1: Horizontal (Left and Right), 2: Both",
        default=0
    )
    parser.add_argument(
        "-wd",
        "--width",
        type=int,
        nargs="?",
        help="Define the width of the resulting image. If not set it will be the width of the text + 10. If the width of the generated text is bigger that number will be used",
        default=-1
    )
    parser.add_argument(
        "-al",
        "--alignment",
        type=int,
        nargs="?",
        help="Define the alignment of the text in the image. Only used if the width parameter is set. 0: left, 1: center, 2: right",
        default=1
    )
    parser.add_argument(
        "-tc",
        "--text_color",
        type=str,
        nargs="?",
        help="Define the text's color, should be either a single hex color or a range in the ?,? format.",
        default = "#282828,#444444"
        #default='#282828'
    )
    return parser.parse_args()

**Comment by Belval** [comment]
Multiple reasons exist to explain the differences you see between the Oxford dataset and the generated examples.

1. There is a 5px margin on top and bottom of the generated text. I am currently looking into fixing this by adding a parameter to let people manage this themselves.
2. Random strings means random strings, if you wish to have common words with symbols in them I would suggest generating your own dictionary and feeding it to `run.py` using the `-i` parameter.
3. White text on dark background is not currently supported this will probably change in the future.

**Comment by Belval** [comment]
About 1, see my reply on issue #31

**Comment by kevgeo** [comment]
@Belval  Hi yes I understood the main difference was because the text is black on white background and not vice-versa. If I am able to do it, I would definitely add a PR. Thanks for the help.

**Comment by Belval** [comment]
Oh that's great news, I didn't know you would be interested in working on it.

I would suggest adding a `-bc` / `--background_color` that takes the same parameters as `--text_color`.

I am opened to ideas!

**Comment by Belval** [comment]
Closing as the issue has gone cold. Feel free to reopen.

**Comment by bharatkumarreddy** [comment]
@kevgeo  Just Curious, Did you able to generate the text like synthetic word Dataset

**Comment by abdksyed** [comment]
Is the background-color supported now???
