### ISSUE TITLE
Can I set the size of the text?

### ISSUE THREAD

**Issue by zhuliqian** [Belval/TextRecognitionDataGenerator#31]

**Comment by Belval** [comment]
You would like smaller text to background ratio?

Font size in determined by using the `-f`, but the size of the image will change too.

**Comment by Oktai15** [comment]
@Belval it would be cool if I could change text size, but image size isn't changed :)

**Comment by Belval** [comment]
I started working on a new parameter called `--margins`

I believe this will allow for the behavior you want.

`-m 0,0,0,0`

![0](https://user-images.githubusercontent.com/5399488/50875646-56dfae80-1397-11e9-989a-4ff74303d8a4.jpg)

`-m 0,5,0,5`

![5](https://user-images.githubusercontent.com/5399488/50875658-619a4380-1397-11e9-83da-caec3a9c94ac.jpg)

`-m 0,10,0,10`

![10](https://user-images.githubusercontent.com/5399488/50875668-6bbc4200-1397-11e9-8360-7245f0fb7c56.jpg)

**Comment by zhuliqian** [comment]
thank you very much,this is great @Belval
