### ISSUE TITLE
run.py arguments in README.md

### ISSUE THREAD

**Issue by prasanthtootcat** [Belval/TextRecognitionDataGenerator#33]
It would be very useful if all the command line arguments were mentioned in the readme file.
Obviously, it could be viewed in the run.py file. Still, a person who is cloning the repo for the first time may not know all the options available.

Thanks!

**Comment by prasanthtootcat** [comment]
Great!

**Comment by Belval** [comment]
It is still a work-in-progress, and maybe not exactly what you had in mind, but the documentation website is live! https://textrecognitiondatagenerator.readthedocs.io/en/latest/index.html

There is a custom repo for it: https://github.com/Belval/TextRecognitionDataGeneratorDocs

**Comment by prasanthtootcat** [comment]
Thanks a lot!
