### ISSUE TITLE
Can the libirary generates pictures with numbers and the font same like the picture below?

### ISSUE THREAD

**Issue by Fighting-JJ** [Belval/TextRecognitionDataGenerator#40]
![gsr0609](https://user-images.githubusercontent.com/17001854/53545460-7fe51a00-3b64-11e9-96f4-5f333317453c.jpg)
583
![default](https://user-images.githubusercontent.com/17001854/53545469-870c2800-3b64-11e9-96c2-8f243b312c78.jpg)
500
@Belval Thanks a lot.

**Comment by Belval** [comment]
The cropping is a bit aggressive compared to what you will usually get from the generator, but yes, you can get similar results.

1. Find the font used in your samples
2. Add it to the font folder and delete all other fonts
3. Generate the data `python3 run.py -c 100 -rs -num`

I'm working on the documentation right now, hopefully that will make it all clearer.

**Comment by Fighting-JJ** [comment]
> The cropping is a bit aggressive compared to what you will usually get from the generator, but yes, you can get similar results.
> 
> 1. Find the font used in your samples
> 2. Add it to the font folder and delete all other fonts
> 3. Generate the data `python3 run.py -c 100 -rs -num`
> 
> I'm working on the documentation right now, hopefully that will make it all clearer.

I got some digit .tff file that looks similarly as the pic showed up. 
but I do not find the tff file that produces the same like the pic showed up.
Tanks  for  your help.
