### ISSUE TITLE
Adding Dilated convolution layer

### ISSUE THREAD

**Issue by thak123** [Belval/TextRecognitionDataGenerator#54]
How can Dilated convolution be employed in the current setting. ?

Came across this repository doing similar ..
https://github.com/MaybeShewill-CV/CRNN_Tensorflow

**Comment by Belval** [comment]
Is it possible that you opened this issue on the wrong repo? https://github.com/Belval/CRNN is the repo where I implemented CRNN. This is a data generator that I used to create more data.

Assuming that it wasn't the case and that you really meant to ask this here. I do not know how dilated convolution could be applied to OCR data generation. Going through the search results on Google it does not seem related.

**Comment by thak123** [comment]
Sorry wrong repo... my fault
