### ISSUE TITLE
Arabic text generator

### ISSUE THREAD

**Issue by niddal-imam** [Belval/TextRecognitionDataGenerator#57]
Hi,

File names generated by the Arabic version of the repo are correct as the word letters are connected. However, text in images has disconnected letters and the words started from left to right. The text in an image should be started from right to left and the letter must be connected. Any suggestion  on how to correct these issues?

Thanks

**Comment by Belval** [comment]
Are you referring to this image from PR #43?
![image](https://user-images.githubusercontent.com/5399488/57194840-7e93ed00-6f19-11e9-83a9-06603a40ea0e.png)

I was able to get the ligatures using the `arabic_reshaper` library.

![ﺑﻴﻴﻀﺔ_2](https://user-images.githubusercontent.com/5399488/57195034-cd428680-6f1b-11e9-9041-063ca2638cc5.jpg)

As for the left-to-right, it's something about the unicode bidirectionnal encoding that I am not doing correctly. I'll play around with it and see if I can get the correct output.

Thank you for your help on this, I have very little knowledge in Arabic.

**Comment by Belval** [comment]
Just noticed that the `arabic_reshaper` library is licensed under the GPL, so I'll have to find another way to make it work anyway.

**Comment by niddal-imam** [comment]
Yes, this is exactly what I meant. Thank you very much for your help.

**Comment by niddal-imam** [comment]
Downloading libraqm dependencies solve the issue.

sudo apt-get install -y libraqm-dev

**Comment by raghada** [comment]
Hello, sorry for bringing this up again. 

I'm a mac user and installed libraqm using the following command:


`brew install freetype harfbuzz fribidi gtk-doc
export XML_CATALOG_FILES="/usr/local/etc/xml/catalog" # for the docs`

Yet, I still get the same output, the text is not RTL, I'm attaching an image below:

![image](https://user-images.githubusercontent.com/12050966/102205083-bb88d980-3edb-11eb-9dfa-64095287fef3.png)

**Comment by yazansayed** [comment]
using `arabic-reshaper` and `python-bidi` solves the problem
```
!pip install arabic-reshaper -q
!pip install python-bidi -q
import arabic_reshaper
from bidi.algorithm import get_display
```

```
fonts=glob.glob("font/*")
text = 'اختبار رقم واحد'
reshaped_text = arabic_reshaper.reshape(text)
bidi_text = get_display(reshaped_text)
generator = GeneratorFromStrings([bidi_text,],language='ar',
                                 fonts=fonts,size=40)
next(generator)[0]
```
![download (1)](https://user-images.githubusercontent.com/50058588/104637054-eddd5080-56ac-11eb-9258-376301f123f2.png)

**Comment by mohammedayub44** [comment]
@Belval  I'm trying to use this from `GeneratorFromRandom` class and doesn't seem to give me the correct Arabic strings. I'm running the following on Jupyter Notebook

`base_generator = GeneratorFromRandom(count=10,length=1,use_numbers=False,use_symbols=False,                                                     use_letters=True, language="ar")`

Most of the images are like below:
![image](https://user-images.githubusercontent.com/7122670/113196758-d8021500-9231-11eb-924c-e1e77877c504.png)

I don't have custom text's like the one shown by @yazansayed  I want to use the built in dictionaires.

Any solution for this ?

Thanks !

**Comment by mohammedayub44** [comment]
After playing around with it more, looks like only Chinese/English language works out of the box , others like Hindi, Korean, french etc. don't show up using the `GeneratorFromRandom` fn.

I'm on Ubuntu 16.04 so I could not install this package `sudo apt-get install -y libraqm-dev`

**Comment by Belval** [comment]
That would make sense, Chinese/Latin support are the scripts that I would consider "officially supported" if you can make a reproducible sample I can try and find the issue for the additional languages.

**Comment by mohammedayub44** [comment]
I was not trying anything custom, just out of the box arguments , something like below - 

Python:

`base_generator = GeneratorFromRandom(count=10,length=1,use_numbers=False,use_symbols=False, use_letters=True, language="ar")`

The Output in this case is as shown above, with just squares in the image

or CLI : 
`trdg -c 10 -w 3 -b 3 -l 'ar'`

Output in this case outputs the filename correctly but image is the same


![image](https://user-images.githubusercontent.com/7122670/113234586-955f2d80-926f-11eb-987c-eaef637818ad.png)
