### ISSUE TITLE
Add argument font in run.py

### ISSUE THREAD

**Issue by JulienCoutault** [Belval/TextRecognitionDataGenerator#59]
Hi,
I used this repo to generate text with only one personal font.

I would like add a argument `font` in `run.py`, if a font is passed in param, it will be the only one used to generate pictures.

I will work in, I saw in readme you want an issue before a PR, so i open it :blush:

**Comment by Belval** [comment]
Excellent! I'm looking forward to it as I have experienced this use case before.

**Comment by Belval** [comment]
Fixed by #60 

Thank you!
