### ISSUE TITLE
Text length

### ISSUE THREAD

**Issue by niddal-imam** [Belval/TextRecognitionDataGenerator#65]
Can I generate texts with a fixed length size?

**Comment by Belval** [comment]
Length in words or length in characters?

**Comment by niddal-imam** [comment]
Length in words.

**Comment by Belval** [comment]
Use the `-w` parameter.

`python3 run.py -w 5` where 5 would be 5 words in each image.

**Comment by niddal-imam** [comment]
Many thanks

**Comment by niddal-imam** [comment]
Sorry Belval, how to generate fixed length in characters?

**Comment by Belval** [comment]
There is no feature to do that at the current time. I'd recommend that you generate a custom dictionary with the strings you want (one per line) and pass it to the CLI using `-i`.

**Comment by niddal-imam** [comment]
Thank you very much.
