### ISSUE TITLE
i got this error, can anyone help me? :((

### ISSUE THREAD

**Issue by minhtn1** [Belval/TextRecognitionDataGenerator#74]
I have this problem when i use handwritten text generate, pls help mee
![image](https://user-images.githubusercontent.com/50301503/60709011-9861a880-9f39-11e9-825e-f7f970ae9837.png)

**Comment by Belval** [comment]
Please checkout the latest version of the code as I cannot support all versions.

Furthermore, it seems like only part of your code changed but that HandwrittenTextGenerator did not.

You can (possibly) just remove the `fit` parameter as it shouldn't be used anymore.

**Comment by minhtn1** [comment]
Ok thank you so much ^^
I have a question that how can i generate some character from my language such as : " ơ " , " ư " , ...
Do i have to retrain the model that generate hw text with dataset from my language ??? 
Looking foward to your reply :D

**Comment by Belval** [comment]
Unfortunately yes, you'd have to find a dataset for your language and retrain the model on it.

See: https://github.com/Grzego/handwriting-generation

**Comment by Belval** [comment]
Closing this issue, as I think it was answered. Feel free to open another if you need help.
