### ISSUE TITLE
Multilingualism is required，Who can help me?

### ISSUE THREAD

**Issue by yufeilongyuan** [Belval/TextRecognitionDataGenerator#76]
I need to mix two languages on a picture, for example, Chinese and English. Then rotate the output 90 degrees, that is, the output in the horizontal case. But I need Chinese rotation, but English does not need rotation. It's like the side of a horizontally placed book, but it contains two languages. Thank you

**Comment by Belval** [comment]
Could you do a quick example using an image manipulation tool like GIMP/Photoshop/Paint/Draw.io?

I am afraid I do not understand what you want to do.

Thank you.

**Comment by Belval** [comment]
Closing for lack of response. Feel free to reopen.
