### ISSUE TITLE
Is there a way to generate janpanese and korean?

### ISSUE THREAD

**Issue by Yang-HangWA** [Belval/TextRecognitionDataGenerator#77]
What should I do if I want to generate janpanese and korean dataset for training ?

**Comment by Belval** [comment]
Unless they have special ligatures, you can just add a case here "jp" for Japan: https://github.com/Belval/TextRecognitionDataGenerator/blob/master/TextRecognitionDataGenerator/run.py#L284

And then create a directory in `fonts/` named `jp/` and add some Japanese fonts in it. Also, add a jp.txt dictionary file to the `dicts/` directory.

Then you can use the `-l jp` parameter to generate Japanese text.
