### ISSUE TITLE
I want to save the pictures in different folders.

### ISSUE THREAD

**Issue by yufeilongyuan** [Belval/TextRecognitionDataGenerator#79]
For example, when 2,000 images are stored in one folder, the rest are stored in another folder, and if the folder does not exist, a new one is created. Excuse me, how to modify the code, thank you.

**Comment by Belval** [comment]
So first thing first, you'll want to edit https://github.com/Belval/TextRecognitionDataGenerator/blob/master/TextRecognitionDataGenerator/data_generator.py#L136 to add this:

```py
try:
    os.makedirs(path)
except OSError as ex:
    if ex.errno == errno.EEXIST:
        pass
    raise ex
```

That will create the directory if it did not exist.

Now for your second requirement, unless you really want to implement it in python, I'd recommend using bash to split your directory, or call `run.py` with the correct output directory.

Something like this:

```bash
#!/bin/bash

for i in {1..10}
do
    python3 run.py --output_dir out_$i -c 2000 ...
done
```

And that will create 10 directories containing 2000 images each.

**Comment by yufeilongyuan** [comment]
I can read the code you wrote. Thank you very much. But I have two questions. The first one is to modify the code like this. Does the image name in each folder coincide with that in other folders? I hope it doesn't overlap, that is to say, each folder has a different image name. Another question is, will the content be synchronized when I generate the tag file separately, as the folder is newly created? Thank you
