### ISSUE TITLE
Capital letters only option

### ISSUE THREAD

**Issue by YacobBY** [Belval/TextRecognitionDataGenerator#81]
Hello, is it possible to generate only capital (upper-case) letters as if CAPS-LOCK is on? I want to generate a dataset for training and I don't need lower-case characters. 

Thanks in advance!

**Comment by Belval** [comment]
I could add that feature for sure, in the meantime, you can add `.upper()` [here](https://github.com/Belval/TextRecognitionDataGenerator/blob/master/TextRecognitionDataGenerator/run.py#L274) and all text will be uppercase.

**Comment by YacobBY** [comment]
Hello, I just made the feature myself, will add it as a pull request in a second
