### ISSUE TITLE
How can I generate pictures contain both Chinese and English？

### ISSUE THREAD

**Issue by edwardelric1202** [Belval/TextRecognitionDataGenerator#85]
Hello, I wonder that if this program can generate pictures contains both Chinese and English? I used command ‘-l cn -l en’ , but it could just recognize the second command, is there any ways to generate Multilingual pictures?

**Comment by Belval** [comment]
All Chinese fonts support English, so what you can do it create a mixed Chinese + English dictionary that you will feed to TextRecognitionDataGenerator using the `-i` parameter.

Remember that you want one word per line, so something like this would work:

```
又
abashments
車
gaoler
gaolering
gaolerness
力
或
種
像
nematoidean
nematology
應
女
教
...
```

For example:

`python3 run.py -i your_mix_dict.txt -c 1000 -w 5 -l cn`
