### ISSUE TITLE
about space character

### ISSUE THREAD

**Issue by wting861006** [Belval/TextRecognitionDataGenerator#88]
I want to generat a character about space.So in dicts/cn.txt  I add a " " in line.But generate image like this:
![image](https://user-images.githubusercontent.com/25969464/62844776-1a41b000-bcf6-11e9-97ac-e93b6d941dd4.png)
label:
465_975.jpg 洱 茬 奖 鸽 振 裤 蛮 ﻿  肄 实
How can I solve the problem?

**Comment by Belval** [comment]
Please provide the font and command that you used to generate this image. Also a reduced test case would help me troubleshoot.

**Comment by wting861006** [comment]
@Belval I use command as :python3 run.py -l cn -c 10000000 -w 10 -wd 280 -t 10 --output_dir images
I think the problem might be caused by character coding.Because I run it with windows10 system,I know the windows system use gbk encoding by default.So I try to run at linux,and sloved it.

**Comment by Belval** [comment]
Support for Windows is somewhat poor due to me not having the OS. So that's worth keeping in mind. Glad you got it sorted out.
