### ISSUE TITLE
How to set the size of font in generated images ?

### ISSUE THREAD

**Issue by Pro-xiaowen** [Belval/TextRecognitionDataGenerator#89]
How to set the size of font in generated images ?
I want to generate the Chinese character  and its font-size is 40
Could you give me some tips?
thanks
@Belval

**Comment by Belval** [comment]
Font size is not a thing in TRDG since it only generates single ligne text. If you want to have bigger text, as in bigger images, you can use ``-f` 256`. If you want to have text that takes a bigger space in the image you can set the margins to 0 using `-m 0,0,0,0`. 

If you can provide an example of what you want I can give you to correct command.

**Comment by Pro-xiaowen** [comment]
> Font size is not a thing in TRDG since it only generates single ligne text. If you want to have bigger text, as in bigger images, you can use `-f 256`. If you want to have text that takes a bigger space in the image you can set the margins to 0 using `-m 0,0,0,0`.
> 
> If you can provide an example of what you want I can give you to correct command.


Thanks for your reply!
![image](https://user-images.githubusercontent.com/25923129/63078915-9e529c80-bf6f-11e9-9e41-ca327889c6d1.png)
what i want to generate is above image,  and you can ingore the background and font-type in above picture.  
You just need to tell me how to set the font size and space. 
Thank you

**Comment by Belval** [comment]
I don't have my computer to test right now, so I might be very off, but I think you want something like:

`python3 run.py -c 1 -w 3 -f 128 -l cn -sw 1 -m 30,5,15,100`

This reads as "Create one image of height 128 containing 3 words/characters in Chinese using 1 full space-width, and a margin of 50 on top, 5 left, 15 bottom and 100 right". You will probably want to play with the margins to get something closer to the image you posted.

**Comment by Pro-xiaowen** [comment]
thanks!!


 
---Original---

**Comment by Belval** [comment]
Closing. Feel free to reopen if you have more questions.
