### ISSUE TITLE
Missing modules for handwritten text generation.

### ISSUE THREAD

**Issue by lqg12138** [Belval/TextRecognitionDataGenerator#9]
When I used run.py, it reported this error, indicating lines 388 and 333.

**Comment by lqg12138** [comment]
python run.py -l cn -c 1000 -w 5
Missing modules for handwritten text generation.
Traceback (most recent call last):
  File "run.py", line 388, in <module>
    main()
  File "run.py", line 333, in main
    lang_dict = load_dict(args.language)
  File "run.py", line 201, in load_dict
    lang_dict = d.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 2: illegal multibyte sequence

**Comment by Belval** [comment]
Hmm that's weird. Can you try with python 3.5+?

**Comment by lqg12138** [comment]
I've been using python 3.6.5

**Comment by Belval** [comment]
From what I could grasp online, the default encoding on your computer is probably gbk and not utf8.

Frankly I didn't know test for that possibility. I'll fix it today and report back.

**Comment by Belval** [comment]
I pushed a new version please retry.

**Comment by lqg12138** [comment]
ok,it's right!
