### ISSUE TITLE
What's the use of this parameter sw?

### ISSUE THREAD

**Issue by ql106** [Belval/TextRecognitionDataGenerator#90]
python3 run.py -c 1 -w 3 -f 128 -l cn -sw 1 -m 30,5,15,100

**Comment by Belval** [comment]
Width of the space character in the generated string.

Setting this to two means that it the space will be twice the width of a regular space. 0 removes space.

**Comment by ql106** [comment]
> 生成字符串中空格字符的宽度。
> 
> 将其设置为两个意味着空间将是常规空间的两倍。0移除空间。

thank you

**Comment by Belval** [comment]
Closing this issue, feel free to reopen if you need clarifications!
